apiVersion: v1
name: s3control-chart
description: A Helm chart for the ACK service controller for  ()
version: 0.0.0-non-release-version
appVersion: 0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/s3control-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/s3control-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name:  Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/s3control-maintainer
keywords:
  - aws
  - kubernetes
  - s3control
